apiVersion: apps/v1
kind: Deployment
metadata:
  name: catto
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catto
  template:
    metadata:
      labels:
        app: catto
    spec:
      containers:
        - name: catto
          image: kvintan/catto:1.0.4
---
apiVersion: v1
kind: Service
metadata:
  name: catto-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: catto
  ports:
    - port: 8080
      targetPort: 8080

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: catto-hpa
  namespace: default
spec:
  minReplicas: 1
  maxReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: catto
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70